// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQJWRB8xJAwpg7EEtPsAwjSdYa25GF2Jw',
    appId: '1:569842060332:web:7e247f6fe523f190f29589',
    messagingSenderId: '569842060332',
    projectId: 'pdpquizapp',
    authDomain: 'pdpquizapp.firebaseapp.com',
    storageBucket: 'pdpquizapp.appspot.com',
    measurementId: 'G-W81V4P26F9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTiVCXf3aCmPtagrRvvOIiCKQ_pcSI5vQ',
    appId: '1:569842060332:android:b28f04e2aeda5726f29589',
    messagingSenderId: '569842060332',
    projectId: 'pdpquizapp',
    storageBucket: 'pdpquizapp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDeL6yLHbbLZMiZmIcWushGHNUMxGk4R-0',
    appId: '1:569842060332:ios:deb600e9032012c9f29589',
    messagingSenderId: '569842060332',
    projectId: 'pdpquizapp',
    storageBucket: 'pdpquizapp.appspot.com',
    iosBundleId: 'com.example.pdpQuizApp',
  );
}
